# Generated by Django 3.0.10 on 2020-09-23 07:08

from django.db import migrations
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_docpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpage',
            name='body',
            field=wagtail.core.fields.StreamField([('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))], blank=True, null=True),
        ),
    ]
