# Generated by Django 3.0.10 on 2020-09-23 10:45

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200923_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReusableMarkdownContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('content', wagtail.core.fields.StreamField([('markdown', wagtail.core.blocks.StreamBlock([('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))]))], blank=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'Reusable Markdown Content',
                'verbose_name_plural': 'Reusable Markdown Content',
            },
        ),
    ]
