# Generated by Django 3.0.10 on 2020-09-23 11:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtailmarkdown.blocks
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0018_auto_20200805_1702'),
        ('website', '0005_reusablemarkdowncontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPageWithReuseSupport',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.CoderedPage')),
                ('reusable_content', wagtail.core.fields.StreamField([('settings', wagtail.core.blocks.StructBlock([('custom_template', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Default')], label='Template', required=False)), ('custom_css_class', wagtail.core.blocks.CharBlock(label='Custom CSS Class', max_length=255, required=False)), ('custom_id', wagtail.core.blocks.CharBlock(label='Custom ID', max_length=255, required=False))])), ('content', wagtail.snippets.blocks.SnippetChooserBlock(website.models.ReusableMarkdownContent))])),
                ('body', wagtail.core.fields.StreamField([('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Doc page with reuse support',
            },
            bases=('coderedcms.coderedpage',),
        ),
    ]
