# Generated by Django 3.0.10 on 2020-09-23 12:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtailmarkdown.blocks
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_docpagewithreusesupport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docpagewithreusesupport',
            name='reusable_content',
        ),
        migrations.AlterField(
            model_name='docpagewithreusesupport',
            name='body',
            field=wagtail.core.fields.StreamField([('markdown', wagtail.core.blocks.StreamBlock([('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))])), ('reuse', wagtail.core.blocks.StructBlock([('settings', wagtail.core.blocks.StructBlock([('custom_template', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Default')], label='Template', required=False)), ('custom_css_class', wagtail.core.blocks.CharBlock(label='Custom CSS Class', max_length=255, required=False)), ('custom_id', wagtail.core.blocks.CharBlock(label='Custom ID', max_length=255, required=False))])), ('content', wagtail.snippets.blocks.SnippetChooserBlock(website.models.ReusableMarkdownContent))]))], blank=True, null=True),
        ),
    ]
