# Generated by Django 3.0.10 on 2020-09-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200924_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindexpage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='articleindexpage',
            name='repeated_item_text',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='repeated_item_text',
        ),
        migrations.RemoveField(
            model_name='docpage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='docpage',
            name='repeated_item_text',
        ),
        migrations.RemoveField(
            model_name='docpagewithmediaandreusesupport',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='docpagewithmediaandreusesupport',
            name='repeated_item_text',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='repeated_item_text',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='repeat_in_subnav',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='repeated_item_text',
        ),
    ]
