# Generated by Django 3.0.10 on 2020-09-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200924_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docpagewithmediaandreusesupportandmenu',
            options={'verbose_name': '(DO NOT USE) Doc page with media and reuse , menu support'},
        ),
    ]
