# Generated by Django 3.0.10 on 2020-09-24 08:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_docpagewithmediaandreusesupportandmenu_add_submenu_item_for_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIDocPage',
            fields=[
                ('docpagewithmediaandreusesupport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.DocPageWithMediaAndReuseSupport')),
            ],
            options={
                'verbose_name': 'CodeRed Web Page',
                'abstract': False,
            },
            bases=('website.docpagewithmediaandreusesupport',),
        ),
        migrations.CreateModel(
            name='ReusableMarkdownCodeEntityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('content', wagtail.core.fields.StreamField([('markdown', wagtail.core.blocks.StreamBlock([('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))]))], blank=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'Reusable Code Entity Content',
                'verbose_name_plural': 'Reusable Code Entity Content',
            },
        ),
    ]
