# Generated by Django 3.0.10 on 2020-09-24 11:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailtrans', '0009_create_initial_language'),
        ('coderedcms', '0018_auto_20200805_1702'),
        ('website', '0016_apidocpage_reusablemarkdowncodeentitycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationPage',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('body', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
        migrations.DeleteModel(
            name='APIDocPage',
        ),
    ]
