# Generated by Django 3.0.10 on 2020-09-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200924_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationpage',
            options={'ordering': ['-first_published_at'], 'verbose_name': '(TEST) Multilingual page'},
        ),
    ]
