# Generated by Django 3.0.10 on 2020-09-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailtrans', '0009_create_initial_language'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('coderedcms', '0018_auto_20200805_1702'),
        ('website', '0018_auto_20200925_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationPage',
        ),
    ]
