# Generated by Django 3.0.10 on 2020-09-25 08:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtailmarkdown.blocks
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0018_auto_20200805_1702'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('website', '0020_languageredirectionpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPageWithMediaAndReuseSupportAndMultilanguage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.CoderedPage')),
                ('body', wagtail.core.fields.StreamField([('markdown', wagtail.core.blocks.StreamBlock([('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))])), ('reuse', wagtail.core.blocks.StructBlock([('settings', wagtail.core.blocks.StructBlock([('custom_template', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Default')], label='Template', required=False)), ('custom_css_class', wagtail.core.blocks.CharBlock(label='Custom CSS Class', max_length=255, required=False)), ('custom_id', wagtail.core.blocks.CharBlock(label='Custom ID', max_length=255, required=False))])), ('content', wagtail.snippets.blocks.SnippetChooserBlock(website.models.ReusableMarkdownContent))])), ('media', website.models.AgoraMediaBlock(icon='media'))], blank=True, null=True)),
                ('french_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('spanish_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Doc page with media and reuse support with multilan',
                'ordering': ['-first_published_at'],
            },
            bases=('coderedcms.coderedpage', models.Model),
        ),
    ]
